I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 243, in script
    menu:
  File "game/powers.rpy", line 86, in execute
    screen map123:
  File "game/powers.rpy", line 86, in execute
    screen map123:
  File "game/powers.rpy", line 88, in execute
    frame:
  File "game/powers.rpy", line 94, in execute
    vbox:
  File "game/powers.rpy", line 96, in execute
    add Input(button=renpy.get_widget("map123")) xalign .5
  File "game/powers.rpy", line 96, in <module>
    add Input(button=renpy.get_widget("map123")) xalign .5
TypeError: get_displayable() takes at least 2 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 243, in script
    menu:
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/ast.py", line 1688, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/exports.py", line 1060, in menu
    rv = renpy.store.menu(new_items)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/exports.py", line 1296, in display_menu
    rv = renpy.ui.interact(mouse='menu', type=type, roll_forward=roll_forward)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/core.py", line 3737, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/screen.py", line 436, in visit_all
    callback(self)
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/core.py", line 3737, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/screen.py", line 447, in per_interact
    self.update()
  File "F:\RenPy\renpy-7.4.11-sdk/renpy/display/screen.py", line 637, in update
    self.screen.function(**self.scope)
  File "game/powers.rpy", line 86, in execute
    screen map123:
  File "game/powers.rpy", line 86, in execute
    screen map123:
  File "game/powers.rpy", line 88, in execute
    frame:
  File "game/powers.rpy", line 94, in execute
    vbox:
  File "game/powers.rpy", line 96, in execute
    add Input(button=renpy.get_widget("map123")) xalign .5
  File "game/powers.rpy", line 96, in <module>
    add Input(button=renpy.get_widget("map123")) xalign .5
TypeError: get_displayable() takes at least 2 arguments (1 given)

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Diplom1 1.0
Sat Jun  4 11:20:49 2022
